name: movies
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  dartz: ^0.10.1
  get_it: ^7.2.0
  shimmer: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.1
  golden_toolkit: ^0.14.0
  network_image_mock: ^2.1.1


flutter:


  uses-material-design: true

